### ISSUE TITLE
goose3 article.top_node and article.cleaned_text returns None

### ISSUE THREAD

**Issue by vasisualy** [goose3/goose3#106]
Goose returns None on some sites (I found three ones), and I don't suppose why((
Code:

from goose3 import Goose
g=Goose()
url='https://www.omskinform.ru/news/128803'
article=g.extract(url)
print(article.top_node)
print()
print(article.cleaned_text)

None

In other cases, goose works great!
Tnx

**Comment by barrust** [comment]
Sorry that it didn't work for you out of the box. It looks like, on the site you linked, that you will need to add your own [known_context_pattern](https://goose3.readthedocs.io/en/latest/code.html#goose3.Configuration.known_context_patterns)

Something along the lines of: 

``` python
from goose3 import Goose
from goose3.configuration import Configuration, ArticleContextPattern

config = Configuration()
config.known_context_patterns = ArticleContextPattern(attr="class", value="n_text")

g = Goose(config)
article = g.extract(url='https://www.omskinform.ru/news/128803') 
print(article.cleaned_text)
```

**Comment by vasisualy** [comment]
Hi, barrust, thank your for answer! But I've seen that way in the other issues, tried, but it still returns None( I solved this task via the other parsing library (using goose3 by default), for example:

from goose3 import Goose
import requests
from readability import Document
from bs4 import BeautifulSoup as bs

g=Goose()

algo=[]
a1_title=[]
a2_cleaned_html=[]
a3_cleaned_text=[]

article=g.extract(url)
    if article.top_node != None:
       algo.append('goose3')
       a3_cleaned_text.append(article.cleaned_text)
       
    else:
        r=requests.get(url)
   
        doc = Document(r.text)
        readable_article=doc.summary()
        algo.append('readability')
        a3_cleaned_text.append(bs(readable_article,"lxml").get_text())

Maybe, the cause of missing Cleaned_text in some sites, is the bad html with unclosed tags in such sites!
Thank you for your attention

**Comment by TomJamesPearce** [comment]
I was testing out Goose, I wanted to see how robust it was, and how it handled adding new tags/attr to parse, and I got stuck on @vasisualy 's example of a failure state.

I wanted to see if it was simply a configuration issue, or if failing that I could repair any malformed HTML

```
from goose3 import Goose
from goose3.configuration import Configuration, ArticleContextPattern
import requests
from bs4 import BeautifulSoup
from pprint import pprint

config = Configuration()
config.known_context_patterns = [ArticleContextPattern(attr="class", value="n_text")]

g = Goose(config)

url = "https://www.omskinform.ru/news/128803"

html = requests.get(url).text

soup = BeautifulSoup(html, "lxml")

cleaned_html = soup.prettify(formatter="html5")

article = g.extract(raw_html=html)
article2 = g.extract(raw_html=cleaned_html)

pprint(article.infos)
pprint(article2.infos)
```

At this point I thought I was going nuts, it still didn't work, custom configs, valid HTML, even a valid article tag!

Turns out it's just a language issue.
Goose finds language metadata of None which I assume means Goose attempts to use English stopwords.

```
from goose3 import Goose

g = Goose({'use_meta_language': False, 'target_language':'ru'})

url = "https://www.omskinform.ru/news/128803"

article = g.extract(url=url)
pprint(article.infos)
```

Behaves exactly as intended

If you really care about robustness at the cost of processing time, I'd suggest that in cases where goose finds data like a description or title in the page metadata but no cleaned text, to fall back on something like langdetect, and then retry with the predicted language.

For example, the above site finds no cleaned_text, but it does find the description.

 ```
from langdetect import detect
detect("Служивые весь день будут охранять треноги во всех районах города. Также камеры поставят на федеральных и региональных автодорогах")
>>> 'ru'
```

Voila
All you need to do then is rerun goose and enforce on the predicted language.

Would the maintainers be interested in incorporating this functionality into Goose?
I may have time to put together a pull request if you're alright with adding langdetect as a dependency.

Due to the extra processing it takes, might want to make it an optional config if you do.

**Comment by barrust** [comment]
We would love PRs! Thanks for tracking this down!
