### ISSUE TITLE
Keep HTML tags, h1, h2 etc tags, images inside article content

### ISSUE THREAD

**Issue by AviRoy1988** [goose3/goose3#112]
We are getting cleared text from Goose which is perfectly ok, but what changes need to make if I want to keep the HTML structure as well for the content section. Like html tags, images

**Comment by barrust** [comment]
Can you explain what you are trying to do? If you want the entire html object it is there in the [raw_html](https://goose3.readthedocs.io/en/latest/code.html#goose3.Article.raw_html) property but if that is the case you likely would just use requests.

**Comment by jaesivsm** [comment]
Hi, I would have the same request. 
I'm using goose in my feed reader ([JARR](https://github.com/jaesivsm/JARR)) and use it for two things: 
 * I use `cleaned_text` for article comparison and clustering => that works greater
 * I reconstruct the cleaned article for the use to read with something like : 

```python
from lxml import etree
article = g.extract(url)
current_node = article.top_node
while True: 
    print(etree.tostring(curr, encoding='utf8').decode("utf8"))
    current_node = current_node.getnext()
    if current_node is None: 
        break
```

That works fine also, but I'm missing all the basic formating and images intended at the origin. 

I tried fiddling in the `cleaners.py` but didn't get far. I still guess for `<h* />` and `<img>` to be kept I would have to override this class right ? 
I'm guessing that the top_node has been used in the processing of the text. Altering it might affect the `cleaned_text` content.
Do you have pointers on how and where I should begin ? And would that be worthy or a PR here ?

**Comment by AviRoy1988** [comment]
> Can you explain what you are trying to do? If you want the entire html object it is there in the [raw_html](https://goose3.readthedocs.io/en/latest/code.html#goose3.Article.raw_html) property but if that is the case you likely would just use requests.

**Comment by AviRoy1988** [comment]
Hi Barrust, I don't need total HTML but the top nodes with HTML structure (at least with tags and images, css class is not required).  As jaesivsm said, I also believe I need to make changes in cleaners.py. I am trying to modify but if you have something in mind, could be more helpful.

**Comment by LaundroMat** [comment]
I'm looking for something similar: I'm extracting an article from a URL, but I would like to keep some basic formatting (paragraphs, headers, ...). Is there a way to tell Goose not to drop certain tags?

**Comment by Jonakemon** [comment]
Have you considered using [top_node](https://goose3.readthedocs.io/en/latest/code.html#goose3.Article.top_node)?

If that doesn't return what you'd like, can you provide me with an example HTML and what you would like to have returned?

**Comment by LaundroMat** [comment]
@Jonakemon [This link](https://vijver.online/onderhoud-vijver-voorjaar-maart-april-mei/) for instance: the main text is detected fine, but formatting and images are not kept.

How can I get all the HTML via `top_node`? `etree.tostring(article.top_node)` returns `<p>` elements and `<style>` attributes, but no `<image>` or `<strong>` tags.

**Comment by Jonakemon** [comment]
The problem lies in line `crawler.py:240`: `self.article._cleaned_text = self.formatter.get_formatted_text()`. Before this line, the top_node is the raw html of the top node. The get_formatted_text method cleans up the content of the top node. @LaundroMat I don't have a way for you right now to get what you want, sorry! But I've added some context for another maintainer - once he responds I can work on a fix for you :) 

@barrust two points:
1. I don't think the get_formatted_text method should change the content of the top node. I don't know what the original intention was behind the method (last commits were in 2013/2018), but it's quite an implicit way to change the content of the top node. Since the result of get_formatted_text is assigned to the _cleaned_text as well, we should _not_ change the content of the top node so that users (like @LaundroMat) can use the top node for their own operations.
2. Additionally, we don't have a way to override the get_formatted_method or the formatter that is used by the crawler. This is a similar issue as in #110. In #110 we talked about users being able to provide their own `ContentExtractor`, while in this issue the user could work around the issue if they could provide their own `OutputFormatter`. I provided an example in #110 on how we could implement it - maybe we can mail/chat about the idea sometime? If we have an idea, I can get working on implementing it.

**Comment by markowanga** [comment]
I think that solution is running line
```python3
# post cleanup
self.article._top_node = self.extractor.post_cleanup()
```
in process method in Crawler class.
I think that we can make new field in article called `top_node_raw` and there put the original node (without cleanup).
