### ISSUE TITLE
Cannot Configure Custom Author Pattern

### ISSUE THREAD

**Issue by p0fi** [goose3/goose3#114]
Hi,

im trying to configure a custom author pattern but it always fails. My code looks like this

```python
from goose3 import Goose
from goose3.configuration import Configuration, AuthorPattern

config = Configuration()
config.known_author_patterns = AuthorPattern(attr="name", value="user", content="content")

g = Goose(config)
article = g.extract(url='https://codeatelier.com/blog/cpp-20-ranges') 
print(article.authors)
```

When running it it always fails with this error message:

```
Traceback (most recent call last):
  File "/Users/thomas/Developer/Privat/test/test2.py", line 5, in <module>
    config.known_author_patterns = AuthorPattern(attr="name", value="user", content="content")
  File "/usr/local/lib/python3.9/site-packages/goose3/configuration.py", line 298, in known_author_patterns
    raise Exception("Unknown type: {}. Use a AuthorPattern.".format(type(val)))
Exception: Unknown type: <class 'goose3.configuration.AuthorPattern'>. Use a AuthorPattern.
```

Is there anything im missing here?

**Comment by barrust** [comment]
@p0fi this is a known issue in [v3.1.6](https://github.com/goose3/goose3/releases/tag/v3.1.6) but has been fixed in the master branch; see [#96](https://github.com/goose3/goose3/pull/96). Until the next version is released, you can either update to the master branch or use a dictionary instead of the AuthorPattern. The next version will have this fixed.

**Comment by p0fi** [comment]
How would I use a dictionary?

**Comment by barrust** [comment]
You can add elements either using a list or single item. That item or items in the list can either be an object of the class, in this case the `AuthorPattern` or a dictionary. 

Something like this should work, though a new version should be released in the next day or so. 

``` python

from goose3 import Goose

with Goose() as g:
    g.config.known_author_patterns = {"attr": "name", "value": "user", "content": "content")
    article = g.extract(url=SOME_URL)
    print(article.authors)
```

**Comment by p0fi** [comment]
Hm your provided example also fails, but with a different error

```
Traceback (most recent call last):
  File "/Users/thomas/Developer/Privat/test/test.py", line 4, in <module>
    g.config.known_author_patterns = {"attr": "name", "value": "user", "content": "content"}
  File "/usr/local/lib/python3.9/site-packages/goose3/configuration.py", line 296, in known_author_patterns
    self._known_author_patterns.insert(0, create_pat_from_dict(val))
  File "/usr/local/lib/python3.9/site-packages/goose3/configuration.py", line 286, in create_pat_from_dict
    return pat
UnboundLocalError: local variable 'pat' referenced before assignment
```

**Comment by barrust** [comment]
Interesting, that *should* have worked but I would have to look into it more. I am hoping to release version 3.1.7 later this evening which hopefully should resolve the issue long term.

**Comment by barrust** [comment]
A new version has been uploaded. You should be able to update to the latest release and this should be resolved. Please re-open the ticket if you still have issues. 

As for the dictionary, apparently it checks for a key of `attribute` instead of `attr`. Not sure this is helpful now as the class is the preferred method.
