### ISSUE TITLE
.movies entity always returns empty list

### ISSUE THREAD

**Issue by ArturasDruteika** [goose3/goose3#121]
```python
    from goose3 import Goose, Configuration


    class ArticleScrapper:

        def __init__(self):
            self.config = Configuration()
            self.config.enable_image_fetching = True
            self.config.browser_user_agent = 'Mozilla 5.0'

            self.g = Goose(config=self.config)

            self.article = None

        def initiate_article(self, url):
            self.article = self.g.extract(url)

        def extract_text(self):
            return self.article.cleaned_text

        def extract_image(self):
            return self.article.top_image.src

        def test_func(self):
            return self.article.movies


    if __name__ == '__main__':
        article_scrapper = ArticleScrapper()

        url = 'https://www.nbcnews.com/politics/white-house/white-house-pitches-biden-s-covid-bill-bipartisan-without-republican-n1258349'

        article_scrapper.initiate_article(url)

        print(article_scrapper.test_func())



```

No matter what url (which contains video) I always get empty list. Is there some kind of functionality error or am I doing something wrong?

**Comment by barrust** [comment]
So, this is an issue with web scrapping. It should pull anything that is a video in the following tags [`iframe`, `embed`, `object`, `video`] but if it is loaded after the html based on a script, then it wouldn't be pulled since it wouldn't exist in the original html. 

That being said, I do not have much experience with the video portion of the code. Any help would be appreciated!

**Comment by barrust** [comment]
I believe in this example, the video is actually an image with an "on-click" set to play it as a video. I am unsure of a good way to handle something like this in this library.
