### ISSUE TITLE
Can't extract hindi news 

### ISSUE THREAD

**Issue by NandhakumarSL** [goose3/goose3#194]
i provide hindi url in goose library it's return always empty text why it's doesn't support indian language please fix this issues

**Comment by barrust** [comment]
Can you provide an example URL? 

It most likely one of a few things, such as: 

1. non-standard article body class or tag  
2. missing stopwords

Without an example, it will be hard to determine what the underlying issue is

**Comment by NandhakumarSL** [comment]
example url : 
  https://www.indiatv.in/india/national/ayodhya-ram-mandir-pran-pratishtha-ceremony-bhagwan-ram-ram-idol-has-been-kept-in-the-garbha-griha-of-temple-2024-01-18-1016965
 barrust sir , please provide support for indian news (for native languages like hindi(hi),tamil(ta),telugu(te),urdu(ur),.....etc)

**Comment by NandhakumarSL** [comment]
https://github.com/codelucas/newspaper/blob/master/newspaper/resources/text/stopwords-hi.txt
barrust sir , it's already exist's in newspaper3k library

**Comment by NandhakumarSL** [comment]
https://khabaruttarakhand.com/kuldeep-martolia-appointed-to-the-post-of-ieec-officer/
barrust sir , this site is not working after you updated stopwords (hindi) why ??? please update it sir

**Comment by barrust** [comment]
Did you try pulling the pull request and the page still didn't work?

**Comment by barrust** [comment]
Using the PR like so works:

``` python
from goose3 import Goose

with Goose() as g:
    g.config.use_meta_language = False
    g.config.target_language = "hi"
    art = g.extract(url="https://khabaruttarakhand.com/kuldeep-martolia-appointed-to-the-post-of-ieec-officer/")
    print(art.cleaned_text)
    print(art.meta_lang)
```

When not overriding the language it doesn't pull anything since the website states that it is in English in the HTML.:

- `<meta property="og:locale" content="en_US">`
- `tml lang="en-US" prefix="og: https://ogp.me/ns#">`

if sites don't help by correctly stating the language codes, then it is up to the user to tell `goose` what language to use. I don't see this as a fault of the library and will continue merging the PR.

**Comment by NandhakumarSL** [comment]
Thanks sir for update and quick resolution for that issue
